### ISSUE TITLE
dockerization

### ISSUE THREAD

**Issue by ristes** [hristijankocev/MCIL#2]
- Dockerbuild
- docker-compose
- redeploy.sh

**Comment by ristes** [comment]
Dockerfile
```
FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} project-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar", "/project-0.0.1-SNAPSHOT.jar"]
```

**Comment by ristes** [comment]
docker-compose.yml
```
version: "3.3"
services:
  project_db:
    image: postgres:10.15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: project
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    container_name: project_db
  project_backend:
    depends_on:
      - project_db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_backend
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://project_db:5432/project"
      - "ELASTICSEARCH_URL=http://project_es:9200"
volumes:
  db-data:
```
